// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Resource.Repository;

#nullable disable

namespace Resource.API.Migrations
{
    [DbContext(typeof(ResourceDbContext))]
    [Migration("20240210103802_TransactionalOutbox")]
    partial class TransactionalOutbox
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Resource.Repository.Model.ResourceDb", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Craftable")
                        .HasColumnType("int");

                    b.Property<int>("Grade")
                        .HasColumnType("int");

                    b.Property<int>("LMD")
                        .HasColumnType("int");

                    b.Property<int?>("Material1")
                        .HasColumnType("int");

                    b.Property<int>("Material1Q")
                        .HasColumnType("int");

                    b.Property<int?>("Material2")
                        .HasColumnType("int");

                    b.Property<int>("Material2Q")
                        .HasColumnType("int");

                    b.Property<int?>("Material3")
                        .HasColumnType("int");

                    b.Property<int>("Material3Q")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Own")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("Material3");

                    b.ToTable("ResourceDb");
                });

            modelBuilder.Entity("Resource.Repository.Model.TransactionalOutbox", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<string>("Messaggio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tabella")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("TransactionalOutboxes");
                });

            modelBuilder.Entity("Resource.Repository.Model.ResourceDb", b =>
                {
                    b.HasOne("Resource.Repository.Model.ResourceDb", "resource")
                        .WithMany("resources")
                        .HasForeignKey("Material3");

                    b.Navigation("resource");
                });

            modelBuilder.Entity("Resource.Repository.Model.ResourceDb", b =>
                {
                    b.Navigation("resources");
                });
#pragma warning restore 612, 618
        }
    }
}
